name: Ubuntu

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update apt
      run: sudo apt-get update
    - name: install cmake dependencies
      run: sudo apt install cmake gcc
    - name: setup build directory
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: build bettermark
      run: cmake --build build --target all -v
    - name: 'export binary'
      uses: actions/upload-artifact@v2
      with:
        name: bettermark
        path: build/bettermark
