name: windows

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup build directory
      run: cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/.local"
    - name: build bettermark
      run: cmake --build build
    - name: 'export binary'
      uses: actions/upload-artifact@v2
      with:
        name: bettermark
        path: build/Debug/bettermark.exe
